// What is bridged onto Asset Hub, and who is holding it.
//
// Asset Hub's `ForeignAssets` registry is keyed by an XCM `Location`, so the key itself says
// where an asset came from. `parents: 2` is a path up past the relay chain and out of
// Polkadot's consensus system — that is what "bridged" means here, and it is a runtime
// guarantee rather than a pattern in today's registry (the source module derives it and
// re-checks it on every read). `parents: 1` is a sibling parachain's own token and is not
// bridged at all. Lumping the two together doubles the apparent bridge inventory.
//
// Five honesty constraints shape everything below, and each of them is a thing the page has to
// say out loud rather than a thing it can quietly get right:
//
//   · THE PAGE OPENS ON DOLLARS, AND MOST ASSETS HAVE NONE. `/api/prices/bridged` values what
//     it can from Hydration read on chain, and on a normal day that is EIGHT of thirty-four.
//     An unpriced asset is ABSENT FROM THE BARS, never drawn at zero — "we could not value
//     this" and "this was worth nothing" are different facts. The headline is therefore a
//     FLOOR, it says so, and the twenty-six absentees are named with the reason each one is
//     absent. There are three different reasons and they are not interchangeable.
//
//   · THE COMPOSITION CHART IS NOT DENOMINATED IN ANYTHING. It used to open this page and it
//     now closes it. `segmentedRows` is drawn there with `scale: 'row'`: each bar is
//     denominated by its OWN supply and encodes composition only — which chain holds what
//     share of this asset. That reads as "every bar is the same length", which is exactly
//     what it is and exactly why it is no longer the first thing on the page. Magnitude in
//     tokens lives in the amount column; magnitude in dollars is the chart at the top, where
//     the rows genuinely share a unit.
//
//   · Σ `ForeignAssets::Account` ≠ `supply` ON SIX OF THIRTY-FOUR ASSETS, AND THAT IS A REAL
//     PROPERTY OF THE CHAIN. The sweep is complete — the number of holder keys read equals the
//     pallet's own `accounts` counter for every asset — and supply is still higher. It was
//     settled by bisection, not by argument: the entire 15.000000 USDT gap appears in ONE
//     block, where supply rose while every holder balance and the account count stayed put. So
//     the residual is split into two things that are NOT the same fact — `onAssetHubAccounts`,
//     which is somebody's balance, and `unaccounted`, which is in no account at all — and they
//     are drawn as two different things: a named segment, and the hatched remainder the chart
//     form exists to expose. Folding them would silently attribute tokens that nobody holds to
//     "somebody on Asset Hub".
//
//   · USDC (1337) AND USDt (1984) ARE NOT BRIDGED. Circle and Tether issue them directly on
//     Asset Hub — no wrapper, no custodian. They are the two biggest stablecoin balances on the
//     chain and they belong to a different question, so they get their own block and never
//     share a bar or a total with anything bridged. Ethereum's USDC exists SEPARATELY in
//     `ForeignAssets`. Two USDCs, three letters, different backing.
//
//   · EVERYTHING IS KEYED BY LOCATION, NEVER BY SYMBOL. Three symbols are currently carried by
//     more than one asset. Summing by ticker adds an Ethereum ERC-20 to a parachain's own token.
//     The same rule is what makes the dollar figures thin, and the page says so rather than
//     hiding it: Hydration registers the same underlying token ONCE PER ROUTE — five USDCs,
//     three WETHs, three WBTCs — and its money market prices at most one leg of each family,
//     never the Snowbridge one this page is about. So the unpriced rows carry a `namesakes`
//     list: the other assets on Hydration wearing the same ticker, with their prices, shown
//     precisely so a reader can see that a price exists and is for something else.

import '../../design/app.css'
import { renderPage } from '../../design/page.js'
import { read } from '../../core/client.js'
import { pageByKey } from '../../sources/pages.js'
import { append, clear, el, notice, statRow, statTile, style } from '../../design/dom.js'
import { segmentedLegend, segmentedRows } from '../../design/charts.js'
import { livenessBanner, livenessNotes } from '../../design/liveness.js'
import { compact, formatCount, formatUtc, money, money2, shortAddr } from '../../core/format.js'

const dash = '—'

/**
 * Let long identifiers break mid-token inside prose.
 *
 * This page's data notes are generated by the source module and rendered verbatim — that is
 * the rule, because a hand-written caveat drifts from the data the first time the data
 * changes. Some of them name an asset by its 54-character storage key, and a hex string is one
 * unbreakable word: at 390 px it made the whole DOCUMENT 78 px wider than the viewport, which
 * is a horizontal scrollbar on every section of the page, not just on the note.
 *
 * `overflow-wrap` is inherited, so this is set once on the container and reaches the text
 * inside a `notice()` without reaching into its markup. It is applied only to PROSE. Tables are
 * deliberately left alone: they already scroll inside `.tablewrap`, and a 25-digit raw supply
 * broken across two lines reads as two numbers.
 */
const wrapAnywhere = (node) => (node ? style(node, 'overflow-wrap:anywhere') : node)

/* ───────────────────────────────────────────────────────────────────────────── labelling ── */

/**
 * The amount column, and the one place a unit decision leaks into a format function.
 *
 * `segmentedRows` takes ONE formatter for every row, but eight of these assets have no
 * `Metadata` entry at all — nothing on chain says how many decimals they use — so their
 * amounts are raw `u128` integers while everybody else's are whole tokens. A raw integer put
 * through `compact()` reads "2100780034897481.00B", which is not a number anybody can hold in
 * their head and is one keystroke away from being mistaken for a scaled figure.
 *
 * So anything at or above 1e15 whole units is rendered in exponential form. That threshold is
 * a rendering choice, not a claim about the asset: the largest scaled supply here is 4.7e8 and
 * the smallest raw one is 3e15, so nothing crosses it by accident today. The row's sublabel
 * says "no decimals" independently, and the table below carries every exact digit.
 *
 * The BOTTOM end matters just as much and is quieter. `compact()` sends anything under ten
 * through `toFixed(2)`, so a real balance of 0.00022022 LBTC renders as "0.00" — a number that
 * reads as nothing next to a bar drawn at full width. On this site `null` is not `0`, and
 * neither is "small": below 0.01 the value keeps three significant figures instead.
 */
function amount(value) {
  const n = Number(value) || 0
  const abs = Math.abs(n)
  if (abs === 0) return '0'
  if (abs >= 1e15) return n.toExponential(2)
  if (abs < 0.01) return n.toPrecision(3)
  return compact(n)
}

/**
 * A raw integer balance rendered EXACTLY in whole units, by moving the decimal point rather
 * than by dividing.
 *
 * This is for the reconciliation column, where the exactness is the argument. `compact()` turns
 * the 11.15 USDC gap into "11" and the whole of the USDT finding — that the gap is *exactly*
 * 15.000000, arriving in one block — cannot be made in a column that has rounded it. Float
 * division cannot be trusted either: 91,090,925,517 at twelve decimals comes back as
 * 0.091090925518, one digit different from what the chain stores.
 *
 * With no decimals on chain there is nothing to shift, so the raw integer is returned as-is.
 */
function exactUnits(raw, decimals) {
  const digits = String(raw)
  if (decimals === null || decimals === undefined) return digits
  const negative = digits.startsWith('-')
  const body = (negative ? digits.slice(1) : digits).padStart(decimals + 1, '0')
  const whole = BigInt(body.slice(0, body.length - decimals)).toLocaleString('en-US')
  const fraction = decimals ? body.slice(body.length - decimals).replace(/0+$/, '') : ''
  return `${negative ? '-' : ''}${whole}${fraction ? `.${fraction}` : ''}`
}

/** The ERC-20 the location points at, already shortened by the source module. */
function contractOf(locationText) {
  const match = /AccountKey20\((0x[0-9a-fA-F…]+)\)/.exec(locationText ?? '')
  return match ? match[1] : null
}

/**
 * What to call an asset. A symbol when the chain provides one — and for the eight that have no
 * metadata, the contract address, because "unknown" eight times over is a list of one thing.
 */
const assetLabel = (asset) => asset.symbol ?? contractOf(asset.locationText) ?? shortAddr(asset.locationHex, 8, 6)

/** "Ethereum mainnet" is what the source module calls it; the bar row has seven rems. */
const networkShort = (asset) => (asset.networkLabel ?? asset.network ?? dash).replace(/ mainnet$/, '')

const scaledAsset = (asset) => asset.decimals !== null

/** A supply, in the unit the chain actually supports for this asset — raw when it supports none. */
const supplyText = (asset) => (scaledAsset(asset) ? amount(asset.supplyScaled) : asset.supply)

/* ──────────────────────────────────────────────────────────────────────── the chart data ── */

/**
 * The series, in a FIXED order that the row filtering never disturbs — colour follows the
 * series slot, not the rank.
 *
 * Asset Hub itself leads, because it is the one segment present on almost every row and it is
 * not a bridge destination: it is what has not left. The parachains follow in the order the
 * source module ranked them, so the ninth and beyond fall into the grey overflow slot, which
 * is the right way round — an overflowing tail should be the smallest holders, never the
 * category the whole page is about.
 */
const buildSeries = (chains) => [
  { label: 'Held on Asset Hub', key: 'asset-hub' },
  ...chains.map((chain) => ({ label: chain.chainName, key: chain.paraId })),
]

/**
 * One row per bridged asset. `total` is the pallet's own `supply`; `segments` are the swept
 * holder balances. They are passed SEPARATELY and the chart checks them — summing the segments
 * and calling that the total would make every row reconcile by construction, which is the one
 * thing this page must not do.
 *
 * Every value in a row comes from the same unit: scaled where the chain says how, raw integers
 * where it does not. Never both in one bar.
 */
function buildRows(assets, holdings, series) {
  const byAsset = new Map()
  for (const holding of holdings) {
    const perChain = byAsset.get(holding.assetKey) ?? new Map()
    const value = holding.amountScaled ?? Number(holding.amount)
    perChain.set(holding.paraId, (perChain.get(holding.paraId) ?? 0) + value)
    byAsset.set(holding.assetKey, perChain)
  }

  return assets.map((asset) => {
    const scaled = scaledAsset(asset)
    const perChain = byAsset.get(asset.locationHex) ?? new Map()
    const segments = series.map((entry) =>
      entry.key === 'asset-hub'
        ? (scaled ? asset.onAssetHubAccountsScaled : Number(asset.onAssetHubAccounts)) ?? 0
        : perChain.get(entry.key) ?? 0,
    )

    return {
      label: assetLabel(asset),
      sublabel: scaled ? networkShort(asset) : 'no decimals',
      // Ignored by `segmentedRows`, kept for this page: whether the row is in whole tokens or
      // in raw integers. Re-deriving it later by comparing the sublabel against a magic string
      // is the kind of thing that survives a copy-edit and then silently stops being true.
      scaled,
      total: scaled ? asset.supplyScaled : Number(asset.supply),
      segments,
      note: `${formatCount(asset.accountsClaimed)} holder account${asset.accountsClaimed === 1 ? '' : 's'} on Asset Hub, all of them swept`,
    }
  })
}

/**
 * Sorted by how WIDELY an asset is distributed, then by how many accounts hold it — both
 * unit-free, because the bars are unit-free. Sorting a mixed-unit list by supply would put
 * 473 million MYTH above 471 WETH and imply a ranking that does not exist without prices.
 */
function sortAssets(assets, rank = (asset) => asset) {
  return [...assets].sort((a, b) => {
    const left = rank(a) ?? {}
    const right = rank(b) ?? {}
    return (
      (right.chains ?? 0) - (left.chains ?? 0) ||
      (right.accountsClaimed ?? 0) - (left.accountsClaimed ?? 0) ||
      assetLabel(a).localeCompare(assetLabel(b))
    )
  })
}

/* ───────────────────────────────────────────────────────────────────────────────── render ── */

function render(host, [inventory, holders, valued]) {
  clear(host)

  if (!inventory.bridged.length) {
    append(
      host,
      notice(
        'warning',
        'Asset Hub has no bridged assets registered',
        'The chain answered and its `ForeignAssets` registry contains nothing with `parents: 2`. That is what the chain says right now; it is not a failure to read it.',
      ),
    )
    return
  }

  const series = buildSeries(holders.chains)
  const rows = buildRows(sortAssets(holders.assets), holders.holdings, series)

  append(
    host,
    // The page's subject leads: what is bridged in, in dollars. Decision 0011 — a dashboard
    // opens on the thing its title names, under at most a title and a sentence or two.
    valueStats(inventory, valued),
    livenessBanner([valued.ok ? valued.data.meta?.liveness : null, inventory.meta?.liveness, holders.meta?.liveness]),
    anomalyNotice(inventory),
    valueCard(valued),
    unpricedCard(valued),
    inventoryCard(inventory, holders),
    issuedCard(inventory),
    // Composition, and it closes the page rather than opening it. Every bar here is the same
    // length by construction and that reads as broken until you have read the caption; it is a
    // real answer to a different question, and a different question belongs further down.
    distributionCard(rows, series, holders, valued.ok ? valued.data.totals.priced : null),
    reconciliationCard(holders),
    notesSection(inventory, holders, valued),
  )
}

/* ──────────────────────────────────────────────── what it is worth ── */

/** The two price paths, in a FIXED slot order so colour never follows the ranking. */
const PRICE_SERIES = [
  { label: 'money-market oracle', key: 'money-market oracle' },
  { label: 'Omnipool implied spot', key: 'Omnipool implied spot' },
]

/**
 * The hero row, and the one number on this page a reader will quote.
 *
 * It is a FLOOR and the tile says so in the same breath, because the alternative — a confident
 * total over a quarter of the inventory — is the exact failure this repository exists to avoid.
 * The excluded figures get tiles of their own rather than a footnote: an amount you can see is a
 * caveat, and an amount you cannot is a rounding error somebody else will find.
 */
function valueStats(inventory, valued) {
  if (!valued.ok) {
    return statRow([
      statTile('Value bridged in', dash, 'Prices could not be read — see the notice below', { hero: true }),
      statTile('Bridged assets', formatCount(inventory.counts.bridged), networksLine(inventory.networks)),
      statTile('No decimals on chain', formatCount(inventory.counts.withoutMetadata), 'nothing on Asset Hub says how to scale them'),
      statTile('Issued here, not bridged', formatCount(inventory.counts.localStables), inventory.localStables.map((coin) => `${coin.symbol} (${coin.assetId})`).join(' · ')),
    ])
  }

  const t = valued.data.totals
  const reasons = [
    t.notOnHydration ? `${t.notOnHydration} not on Hydration` : null,
    t.noVenue ? `${t.noVenue} in no priced venue` : null,
    t.noDecimals ? `${t.noDecimals} with no decimals here` : null,
    t.decimalsDisagree ? `${t.decimalsDisagree} whose decimals disagree` : null,
  ].filter(Boolean)

  return statRow([
    statTile(
      'Value bridged in, at least',
      // `money()`, not `money2()`. The hero type size is large enough that a nine-character
      // figure with separators clips at 1280px — "$16,002,..." — and a headline that has lost
      // its last digits is worse than a rounded one. The exact figure is one line below.
      t.pricedUsd === null ? dash : money(t.pricedUsd),
      `${t.pricedUsd === null ? '' : `${money2(t.pricedUsd)} exactly. `}${formatCount(t.priced)} of ${formatCount(t.assets)} assets could be valued — a floor, not a total. The other ${formatCount(t.unpriced)} are absent from the bars, not worth zero.`,
      { hero: true },
    ),
    statTile('Could not be valued', `${formatCount(t.unpriced)} assets`, reasons.join(' · ')),
    statTile(
      'Priced, but unscalable',
      t.excludedNoDecimalsUsd === null ? dash : money2(t.excludedNoDecimalsUsd),
      'what three of the metadata-less assets would be worth at Hydration’s decimals. Another chain’s divisor, so it is stated and not counted.',
    ),
    statTile('Issued here, not bridged', formatCount(inventory.counts.localStables), inventory.localStables.map((coin) => `${coin.symbol} (${coin.assetId})`).join(' · ')),
  ])
}

/**
 * One bar per bridged asset it was possible to value, on ONE shared linear scale from zero,
 * largest first. This is the chart the page exists for.
 *
 * Colour is the price’s PROVENANCE, not the asset. Half the value here comes from the Omnipool’s
 * implied spot rather than from the money-market oracle, and those are two different
 * constructions that agree to about half a percent — close enough to use and not close enough to
 * merge. Putting the venue in the bar means a reader cannot read the total without also seeing
 * which half of it rests on which method.
 *
 * An unpriced asset is NOT a row here. There is no zero-length bar and no grey placeholder: it
 * would sit on a linear scale at the same place as an asset genuinely worth nothing, and those
 * are different facts. They get their own card, immediately below, with the reason each.
 */
function valueCard(valued) {
  if (!valued.ok) {
    return el(
      'section.card',
      null,
      el('header', null, el('h2', { text: 'What is bridged in, in dollars' })),
      notice(
        valued.kind === 'transport' ? 'warning' : 'critical',
        'No dollar figures on this read',
        valued.message,
        valued.advice,
        'Everything below is unaffected: it comes from Asset Hub directly and needs no price. What is missing is only the valuation.',
      ),
    )
  }

  const { assets, totals, oracle, crossCheck, hydrationChain } = valued.data
  const priced = assets.filter((a) => a.priceStatus === 'priced' && a.usd !== null)

  if (!priced.length) {
    return el(
      'section.card',
      null,
      el('header', null, el('h2', { text: 'What is bridged in, in dollars' })),
      notice(
        'warning',
        'Nothing on this page could be valued',
        `Hydration answered and prices ${formatCount(oracle.quotedAssets)} of the ${formatCount(oracle.registeredAssets)} assets in its registry, and none of them is one of these ${formatCount(totals.assets)}. That is a fact about which assets have a market, not a failure to read one.`,
      ),
    )
  }

  const rows = priced.map((asset) => ({
    label: assetLabel(asset),
    // Amount only. The venue is the bar's COLOUR and the legend names it; repeating it here
    // pushed the sublabel past the column and it clipped to "24.00M TRAC ·…".
    sublabel: `${amount(asset.supplyScaled)} ${asset.symbol ?? 'units'}`,
    total: asset.usd,
    // One value, in the slot belonging to the venue that priced it. The other slot is 0 and
    // `segmentedRows` filters zero-width segments out, so nothing is drawn for it.
    segments: PRICE_SERIES.map((entry) => (entry.key === asset.priceSource ? asset.usd : 0)),
    note: `${asset.symbol ?? 'this asset'} at $${Number(asset.price).toPrecision(6)} per token, from Hydration’s ${asset.priceSource}\nHydration asset ${asset.hydrationId} · ${asset.locationText}`,
  }))

  const plot = el('div')
  const legendTotals = PRICE_SERIES.map((entry) =>
    priced.filter((a) => a.priceSource === entry.key).reduce((sum, a) => sum + a.usd, 0),
  )

  const card = el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: 'What is bridged in, in dollars' }),
      el('p.note', {
        text:
          `One bar per bridged asset, on one shared linear scale from zero, largest first — so these bars ARE comparable with each other, which is the one thing the composition chart at the foot of this page cannot do. Prices are read live from Hydration at block ${formatCount(hydrationChain.block)}: the money-market oracle where it carries the asset, and the Omnipool’s own implied spot where it does not. Each bar is coloured by which of the two priced it.`,
      }),
      el('p.note', {
        text:
          `${formatCount(totals.unpriced)} of the ${formatCount(totals.assets)} bridged assets are NOT on this chart. They are not drawn at zero and they are not folded into the total: an asset this site cannot value and an asset worth nothing are different facts, and a linear scale from zero cannot tell them apart. The next card names every one of them and says which of four different things is wrong — they are not interchangeable and “unpriced” is not one answer.`,
      }),
    ),
    segmentedLegend(PRICE_SERIES, legendTotals, money),
    plot,
  )

  const tally = segmentedRows(plot, {
    rows,
    series: PRICE_SERIES,
    format: money,
    // Shared, deliberately, and it is the whole point of the chart. Every row is in dollars.
    scale: 'shared',
    residualLabel: 'not attributed to a venue',
  })

  const faint = tally.faint
  append(
    card,
    faint
      ? el('p.note', {
          text: `${faint} of the ${rows.length} bars draw under 2 % of the largest and are held at the minimum width that stays visible — read the figure at the end of the row rather than the length of the bar. The concentration is the finding: the top three assets are ${((rows.slice(0, 3).reduce((s, r) => s + r.total, 0) / totals.pricedUsd) * 100).toFixed(0)} % of everything that could be valued.`,
        })
      : null,
    crossCheckNote(crossCheck, totals),
    el('p.note', {
      text:
        'The oracle is a stepped feed — about eighteen updates a day, not one per block — so a fast move can be up to an hour old here. It is the same feed for every asset, so the ranking moves less than the total does. Asset Hub and Hydration are also read a few seconds apart, so a transfer landing between the two moves a supply without moving its price.',
    }),
  )
  return card
}

/**
 * The two price paths, checked against each other on every read and reported whether or not they
 * agree. Four assets are in both venues, so this is a real reconciliation rather than a promise —
 * and half the value on the chart above rests on the path that is NOT the oracle.
 */
function crossCheckNote(crossCheck, totals) {
  if (!crossCheck?.length) {
    return el('p.note', {
      text:
        'No asset is currently in both venues, so the two price paths cannot be checked against each other on this read. Every figure above therefore rests on one construction with nothing to compare it to.',
    })
  }
  const worst = crossCheck[0]
  const share = totals.pricedUsd ? (totals.byOmnipoolUsd / totals.pricedUsd) * 100 : null
  return el('p.note', {
    text:
      `${formatCount(crossCheck.length)} assets are priced by BOTH paths, so the two are checked against each other on every read: the largest disagreement right now is ${worst.symbol ?? `asset ${worst.id}`} at ${worst.differencePct.toFixed(2)} % (oracle $${Number(worst.oracle).toPrecision(6)}, Omnipool $${Number(worst.spot).toPrecision(6)}). That matters here because ${share === null ? 'part' : `${share.toFixed(0)} %`} of the total above comes from the Omnipool path rather than from the oracle. The two are never merged — each number keeps the label of the venue it came from.`,
  })
}

const networksLine = (networks) => networks.map((network) => `${network.assets} from ${network.label.replace(/ mainnet$/, '')}`).join(', ')

/**
 * The registry invariant, re-derived on every read by the source module. Empty on every read so
 * far — which is exactly why it renders as nothing rather than as a reassuring green box.
 */
function anomalyNotice(inventory) {
  if (!inventory.anomalies?.length && inventory.complete !== false) return null
  return notice(
    'critical',
    inventory.anomalies?.length ? `${inventory.anomalies.length} registry entries do not fit the runtime’s own rule` : 'This read of the registry is incomplete',
    inventory.anomalies?.length
      ? 'Asset Hub’s `ForeignAssets` accepts only three creation origins, and each pins `parents` exactly — so a `parents: 2` key that does not open with a non-Polkadot `GlobalConsensus` can only have come from a governance `force_create`. These keys are listed rather than counted, because counting them would quietly change what "bridged" means on this page.'
      : 'The registry was not enumerated to the end, so the counts below are a lower bound rather than the inventory.',
    ...(inventory.anomalies ?? []).map((entry) => entry.locationText ?? entry.locationHex ?? String(entry)),
  )
}

/* ─────────────────────────────────────────────────── what could not be valued, and why ── */

/**
 * Rule 3, given a whole card instead of a footnote.
 *
 * Three quarters of this registry has no dollar figure and there are FOUR different reasons for
 * that, which are not interchangeable and must not be summarised as "unpriced":
 *
 *   no-decimals        Asset Hub itself does not say how many decimals the asset uses, so its
 *                      raw supply is not a token count yet, let alone a dollar figure. This is
 *                      upstream of pricing entirely.
 *   not-on-hydration   Hydration's registry has no entry for this location. Often it has an
 *                      entry for the same TICKER, and that is a different asset.
 *   no-venue           Hydration has the asset and prices it in neither the money market nor
 *                      the Omnipool.
 *   decimals-disagree  Both chains have it and they disagree about the divisor. Refused: the
 *                      product would be wrong by a factor of ten to the n and render perfectly.
 *
 * The `namesakes` column is the load-bearing one and it exists because of a specific reader
 * reaction. Hydration visibly prices something called WBTC; a blank next to this page's WBTC
 * reads as a bug. It is not: Hydration registers the same underlying token once per ROUTE, and
 * its money market took the Wormhole leg while this page is about the Snowbridge leg. Showing
 * the namesake and its price is the only way to make that visible — and showing it is the exact
 * opposite of using it.
 */
const REASON = {
  'no-decimals': 'Asset Hub publishes no decimals for it',
  'not-on-hydration': 'not in Hydration’s registry under this location',
  'no-venue': 'on Hydration, but in neither priced venue',
  'decimals-disagree': 'the two chains disagree about its decimals',
}

/** One namesake, in as few characters as a table cell can afford. The full form is on `title`. */
const namesakeLine = (n) =>
  `${n.symbol} #${n.id} · ${n.usd === null ? 'also unpriced' : `$${Number(n.usd).toPrecision(6)}`} · ${n.route}`

/**
 * One, because a five-USDC row pushes every other column off the scroll box — and the one is the
 * most informative one: the server sorts namesakes by price descending, so the priced leg leads
 * and the cell answers "a price for this ticker exists, and here is which asset it belongs to".
 * The whole list is on the cell's `title`.
 */
function namesakeText(namesakes) {
  if (!namesakes.length) return dash
  const rest = namesakes.length - 1
  return `${namesakeLine(namesakes[0])}${rest ? ` · +${rest} more` : ''}`
}

function unpricedCard(valued) {
  if (!valued.ok) return null
  const { assets, totals, unscalable } = valued.data
  const missing = assets.filter((a) => a.priceStatus !== 'priced')
  if (!missing.length) return null

  // Ordered as a narrative from "nearly" to "not at all", rather than alphabetically. Sorting
  // by label put the eight metadata-less rows — whose label is a 42-character hex string — above
  // every recognisable ticker, so the first thing a reader met was the least legible thing here.
  const ORDER = ['no-venue', 'not-on-hydration', 'decimals-disagree', 'no-decimals']
  const ordered = [...missing].sort(
    (a, b) =>
      ORDER.indexOf(a.priceStatus) - ORDER.indexOf(b.priceStatus) ||
      assetLabel(a).localeCompare(assetLabel(b)),
  )

  const body = el('tbody')
  for (const asset of ordered) {
    const namesakes = asset.namesakes ?? []
    append(
      body,
      el(
        'tr',
        null,
        el('td.mono', { text: assetLabel(asset) }),
        el('td.num.mono', {
          // A raw u128 printed in full is 25 unreadable digits and it is one glance away from
          // being taken for a scaled figure. `amount()` sends anything at or above 1e15 through
          // exponential form for exactly that reason; the exact digits stay on the title and in
          // the registry table below.
          text: scaledAsset(asset) ? amount(asset.supplyScaled) : amount(Number(asset.supply)),
          title: `${asset.supply} raw units${scaledAsset(asset) ? ` at ${asset.decimals} decimals` : ', and no decimals on chain to scale them by'}`,
        }),
        el(
          'td',
          null,
          el('span.pill', { text: asset.priceStatus, data: { tone: asset.priceStatus === 'decimals-disagree' ? 'critical' : 'warning' } }),
          document.createTextNode(` ${REASON[asset.priceStatus] ?? ''}`),
        ),
        el('td', { text: namesakeText(namesakes), title: namesakes.map(namesakeLine).join('\n') }),
      ),
    )
  }

  const withNamesakes = missing.filter((a) => a.namesakes?.length).length
  const pricedNamesakes = missing.filter((a) => (a.namesakes ?? []).some((n) => n.usd !== null)).length
  const knownDivisor = unscalable.filter((u) => u.wouldBeUsd !== null)

  return el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: `The ${formatCount(missing.length)} assets that could not be valued` }),
      el('p.note', {
        text:
          'Every one of them, named, with which of four things is wrong. None of them is drawn at zero anywhere on this page and none is inside the total above — an asset this site could not value is a different fact from an asset worth nothing, and folding the two together is how a dollar figure comes to describe less than it claims.',
      }),
    ),
    pricedNamesakes
      ? notice(
          'info',
          `Hydration does price something with the same ticker as ${formatCount(pricedNamesakes)} of these — and it is a different asset`,
          'Hydration registers the same underlying token once per ROUTE, not once. On the last read it carried five USDCs, three WETHs, three WBTCs, three USDTs and three DAIs — arriving via Snowbridge, via Wormhole, via Acala, issued natively on Asset Hub, or issued by the token’s own parachain — as separate registry ids with separate liquidity. Its money market prices at most one leg of each family, and it is never the Snowbridge leg this page is about.',
          'So the right-hand column is a diagnostic and never a price. Substituting the Wormhole WBTC’s price onto the Snowbridge WBTC would be within a fraction of a percent of right today, would render perfectly, and would be a claim about bridge risk that nothing here has evidence for. This is the same rule as “never sum by ticker”, one level up: the underlying contract address is not a key either.',
        )
      : null,
    knownDivisor.length
      ? notice(
          'warning',
          `${formatCount(knownDivisor.length)} of these have a price but no divisor, and would be worth about ${money2(totals.excludedNoDecimalsUsd)}`,
          `Asset Hub carries no metadata entry for them, so the chain holding the supply does not say what one whole token is. Hydration’s registry does — ${knownDivisor.map((u) => `${u.hydrationSymbol} at ${u.hydrationDecimals}`).join(', ')} — and at those decimals they would come to ${money2(totals.excludedNoDecimalsUsd)}, against ${money2(totals.pricedUsd)} measured above.`,
          'That figure is stated here and used nowhere. It rests on a second chain’s claim about the divisor, and a wrong divisor is a silent factor of ten to the n: at eighteen decimals one of these is 2.1 million tokens and at eight it is 21 thousand billion. Both render perfectly. Settling it needs the ERC-20’s own `decimals()`, which is on Ethereum and not on any chain this site reads.',
        )
      : null,
    el(
      'div.tablewrap.scroll-y',
      null,
      el(
        'table.data',
        null,
        el(
          'thead',
          null,
          el(
            'tr',
            null,
            el('th', { text: 'Asset' }),
            el('th.num', { text: 'Supply' }),
            el('th', { text: 'Why there is no dollar figure' }),
            el('th', { text: 'Same ticker on Hydration (a different asset)' }),
          ),
        ),
        body,
      ),
    ),
    el('p.note', {
      text:
        withNamesakes
          ? `${formatCount(withNamesakes)} of these carry a same-ticker entry on Hydration. Matching here is done on the raw SCALE bytes of the XCM location, which is the only key that identifies an asset across two chains — three tickers on this page are already carried by more than one asset within Asset Hub alone.`
          : 'Matching is done on the raw SCALE bytes of the XCM location, which is the only key that identifies an asset across two chains.',
    }),
  )
}

/* ──────────────────────────────────────────────────────────────────── where the assets sit ── */

function distributionCard(rows, series, holders, pricedCount = null) {
  const plot = el('div')
  const tally = segmentedRows(plot, {
    rows,
    series,
    format: amount,
    residualLabel: 'in no account at all',
    // A UNIT DECISION, not a display preference. See the file header.
    scale: 'row',
  })

  // What `scale: 'shared'` would have produced, computed over the assets that CAN be scaled so
  // the diagnostic is about mixing tokens rather than about mixing raw and scaled integers.
  const inTokens = rows.filter((row) => row.scaled)
  const largest = Math.max(...inTokens.map((row) => row.total), 1)
  const wouldBeFaint = inTokens.filter((row) => row.total / largest < 0.02).length

  // The chart's own arithmetic against the server's. It reconciles in floats over scaled
  // amounts; the payload reconciles in BigInt over raw integers. Agreement is worth something
  // precisely because the two do not share a code path.
  const agrees = tally.reconciled === holders.reconciliation.exact && tally.short === holders.reconciliation.mismatched.length && tally.over === 0

  const chainCounts = new Map(holders.chains.map((chain) => [chain.paraId, chain.assets]))
  const onAssetHub = holders.assets.filter((asset) => BigInt(asset.onAssetHubAccounts) > 0n).length
  const legendTotals = series.map((entry) => (entry.key === 'asset-hub' ? onAssetHub : chainCounts.get(entry.key) ?? 0))

  return el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: 'Where each bridged asset currently sits' }),
      el('p.note', {
        text:
          'A different question from the chart at the top, and the reason this one is down here. One bar per bridged asset, split by whichever parachain sovereign account is holding it, with everything still on Asset Hub as the leading segment. The segments are the swept holder balances and the bar is the pallet’s own supply figure — they are read separately and checked against each other, so a bar that does not fill is supply that no account holds.',
      }),
      el('p.note', {
        text:
          `EVERY BAR HERE IS THE SAME LENGTH, and that is the chart working rather than failing: each one is denominated by its OWN supply, so what it encodes is composition and nothing else. These rows have no shared unit — only ${formatCount(inTokens.length)} of them can be scaled at all, and denominated instead by the largest supply among those, ${formatCount(wouldBeFaint)} would draw under 2 % of the track, not because they are small but because 473 million MYTH and 471 WETH are not the same thing. Magnitude in tokens is in the amount column next to its unit; magnitude in dollars is the chart at the top of this page, where the rows do share a unit and only ${formatCount(pricedCount ?? 0)} of them appear.`,
      }),
    ),
    segmentedLegend(series, legendTotals, (count) => (count === 1 ? '1 asset' : `${formatCount(count)} assets`)),
    plot,
    el('p.note', {
      text: agrees
        ? `${tally.reconciled} of ${rows.length} bars are filled exactly by their segments; ${tally.short} fall short and none overflow. That matches the server’s own reconciliation, which is computed in integer arithmetic over raw balances rather than in the scaled figures drawn here.`
        : `⚠ This chart counts ${tally.reconciled} reconciled and ${tally.short} short, and the payload’s own reconciliation counts ${holders.reconciliation.exact} and ${holders.reconciliation.mismatched.length}. Those two are computed differently — floats over scaled amounts here, integers over raw balances there — and they should not disagree. Trust the table.`,
    }),
    el('p.note', { text: shortfallNote(holders) }),
    el('p.note', {
      text:
        'The smallest segments are floored to one pixel rather than rounded away, so they are deliberately not to scale: a real balance drawing as nothing would read as zero, and on this site a small number and no number are different facts.',
    }),
  )
}

/**
 * The one thing this chart cannot show, said in words instead.
 *
 * The hatched remainder is the whole reason for this chart form — and here the six real
 * shortfalls are thousandths of a percent of supply, which at any sane width is the one-pixel
 * floor. Every bar therefore LOOKS full. Without this sentence a reader would take the picture
 * as evidence that everything reconciles, which is the exact opposite of the finding.
 */
function shortfallNote(holders) {
  const short = holders.assets.filter((asset) => !asset.reconciliation.holderSumMatchesSupply && Number(asset.supply) > 0)
  const empty = holders.assets.filter((asset) => asset.supply === '0').length
  const shares = short.map((asset) => (Number(asset.unaccounted) / Number(asset.supply)) * 100).sort((a, b) => a - b)

  const gap = shares.length
    ? `The ${shares.length} bars that do not reconcile fall short by between ${shares[0].toPrecision(2)} % and ${shares[shares.length - 1].toPrecision(2)} % of their own supply, which at this width is the one-pixel floor — the hatched remainder is drawn but it is not visible, so every bar here looks full. That finding is carried by the table below, not by the picture.`
    : 'Every bar is filled exactly by its segments.'

  const zero = empty
    ? ` ${empty} assets are registered with a supply of zero and draw an empty track: nothing is bridged in them at the moment, which is the chain saying so rather than a value this page could not read.`
    : ''

  return `${gap}${zero}`
}

/* ─────────────────────────────────────────────────────────────────────── the reconciliation ── */

function reconciliationCard(holders) {
  const mismatched = new Map(holders.reconciliation.mismatched.map((entry) => [entry.locationHex, entry]))
  const gaps = holders.assets.filter((asset) => mismatched.has(asset.locationHex))

  const body = el('tbody')
  for (const asset of gaps) {
    const scaled = scaledAsset(asset)
    const share = Number(asset.supply) > 0 ? (Number(asset.unaccounted) / Number(asset.supply)) * 100 : null
    append(
      body,
      el(
        'tr',
        null,
        el('td.mono', { text: assetLabel(asset) }),
        // Every digit the chain stores, shifted rather than divided. See `exactUnits`.
        el('td.num.mono', { text: exactUnits(asset.unaccounted, asset.decimals) }),
        el('td', { text: scaled ? `${asset.symbol ?? 'units'}, at ${asset.decimals} decimals` : 'raw units — no decimals on chain' }),
        // Two significant figures rather than three decimal places. Fixed decimals would floor
        // three of these six to "<0.001 %", which throws away the two orders of magnitude
        // between the smallest gap and the largest — the one thing this column is here to show.
        el('td.num', { text: share === null ? dash : `${share.toPrecision(2)} %` }),
        el('td.num', { text: `${formatCount(asset.holdersSwept)} / ${formatCount(asset.accountsClaimed)}` }),
      ),
    )
  }

  const decomposition = el('tbody')
  for (const asset of sortAssets(holders.assets)) {
    const value = (raw, scaledValue) => (scaledAsset(asset) ? amount(scaledValue) : raw)
    append(
      decomposition,
      el(
        'tr',
        null,
        el('td.mono', { text: assetLabel(asset) }),
        el('td.num.mono', { text: supplyText(asset) }),
        el('td.num.mono', { text: value(asset.sovereignTotal, asset.sovereignTotalScaled) }),
        el('td.num.mono', { text: value(asset.onAssetHubAccounts, asset.onAssetHubAccountsScaled) }),
        el('td.num.mono', { text: value(asset.unaccounted, asset.unaccountedScaled) }),
        el(
          'td',
          null,
          el('span.pill', {
            text: asset.reconciliation.holderSumMatchesSupply ? 'exact' : 'short',
            data: { tone: asset.reconciliation.holderSumMatchesSupply ? 'good' : 'warning' },
          }),
        ),
      ),
    )
  }

  return el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: 'Supply that is in no account at all' }),
      el('p.note', {
        text:
          'For every bridged asset the holder map was swept whole — the number of keys read equals `AssetDetails.accounts`, the pallet’s own counter — and then compared against `AssetDetails.supply`. On 28 of 34 assets those agree to the last unit. On six they do not, and supply is always the larger side.',
      }),
    ),
    wrapAnywhere(
      notice(
        'info',
        'This is a property of the chain, not a gap in the read',
        'It was settled by bisection rather than by argument (Asset Hub, 2026-08-20). The whole of the Snowbridge USDT gap — exactly 15.000000 USDT — appears in a single block, #14,915,236 on 2026-04-24, where `supply` rose by 15.000000 while every one of the 44 holder balances and the account count stayed unchanged. The only non-inherent extrinsic in that block is `ParachainSystem::set_validation_data`, i.e. inbound XCM. So supply on this pallet can be minted without any account being credited. The mechanism inside XCM is not established here.',
        'What that means for reading this page: the sign is always the same, supply above the accounts and never below, so this column is a CEILING on how much of a bridged asset is claimed to exist beyond what anybody demonstrably holds. It is at most a few thousandths of a percent of supply today, and it is shown rather than absorbed into the Asset Hub segment — absorbing it would silently attribute tokens that are in no account to somebody who holds them.',
      ),
    ),
    el(
      'div.tablewrap',
      null,
      el(
        'table.data',
        null,
        el(
          'thead',
          null,
          el(
            'tr',
            null,
            el('th', { text: 'Asset' }),
            el('th.num', { text: 'In no account' }),
            el('th', { text: 'Unit' }),
            el('th.num', { text: 'of supply' }),
            el('th.num', { text: 'Keys swept' }),
          ),
        ),
        body,
      ),
    ),
    el(
      'details.data-table',
      null,
      el('summary', { text: `Supply decomposed for all ${holders.assets.length} bridged assets` }),
      el(
        'div.tablewrap.scroll-y',
        null,
        el(
          'table.data',
          null,
          el(
            'thead',
            null,
            el(
              'tr',
              null,
              el('th', { text: 'Asset' }),
              el('th.num', { text: 'Supply' }),
              el('th.num', { text: 'Parachain sovereigns' }),
              el('th.num', { text: 'Asset Hub accounts' }),
              el('th.num', { text: 'In no account' }),
              el('th', { text: 'Σ = supply' }),
            ),
          ),
          decomposition,
        ),
      ),
    ),
    el('p.note', {
      text:
        '“Asset Hub accounts” is every non-sovereign holder — people, `AssetConversion` pool accounts, pallet accounts — and is a residual, not one account and not a treasury. It is a different fact from the column beside it, which is nobody’s balance, and the two are never added together here.',
    }),
  )
}

/* ─────────────────────────────────────────────────────────────────────────── the inventory ── */

function inventoryCard(inventory, holders) {
  const chainsByAsset = new Map(holders.assets.map((asset) => [asset.locationHex, asset]))
  const holdingChains = new Map()
  for (const holding of holders.holdings) {
    const list = holdingChains.get(holding.assetKey) ?? []
    list.push(holding.chainName)
    holdingChains.set(holding.assetKey, list)
  }

  const body = el('tbody')
  for (const asset of sortAssets(inventory.bridged, (entry) => chainsByAsset.get(entry.locationHex))) {
    const chains = holdingChains.get(asset.locationHex) ?? []
    append(
      body,
      el(
        'tr',
        null,
        el('td.mono', { text: assetLabel(asset) }),
        el('td', { text: asset.hasMetadata ? asset.name ?? dash : 'no metadata on chain' }),
        el('td', { text: networkShort(asset) }),
        el(
          'td.num',
          null,
          asset.decimals === null
            ? el('span.pill', { text: 'none on chain', data: { tone: 'warning' } })
            : document.createTextNode(String(asset.decimals)),
        ),
        el('td.num.mono', { text: supplyText(asset), title: `${asset.supply} raw units` }),
        el('td.num', { text: formatCount(asset.accounts) }),
        el('td', { text: chains.length ? chains.join(', ') : 'none' }),
        // Last, not third. The location is the KEY and it stays on the row in full — but it is
        // sixty characters of near-identical prefix on thirty-three of these rows, and in the
        // third column it pushed supply and holders off the end of the scroll box, so the one
        // thing a reader came for was the one thing not on screen.
        el('td.mono', { text: asset.locationText, title: asset.locationHex }),
      ),
    )
  }

  const siblings = el('tbody')
  for (const asset of inventory.sibling) {
    append(
      siblings,
      el(
        'tr',
        null,
        el('td.mono', { text: assetLabel(asset) }),
        el('td', { text: asset.name ?? dash }),
        el('td.num', { text: asset.siblingParaId === null ? dash : formatCount(asset.siblingParaId) }),
        el('td.num', { text: asset.decimals === null ? dash : String(asset.decimals) }),
        el('td.num.mono', { text: supplyText(asset) }),
        el('td.num', { text: formatCount(asset.accounts) }),
      ),
    )
  }

  return el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: 'The registry, asset by asset' }),
      el('p.note', {
        text:
          `All ${inventory.counts.bridged} bridged assets, keyed by the XCM location decoded out of the storage key itself. Supply is what the pallet has minted on Asset Hub — for a Snowbridge asset that is the amount currently locked on the Ethereum side, and it is not a claim about the asset’s supply anywhere else. The holder count is the pallet’s own, and it counts accounts rather than people.`,
      }),
    ),
    inventory.counts.withoutMetadata
      ? notice(
          'warning',
          `${inventory.counts.withoutMetadata} of these assets have no metadata entry at all`,
          'Nothing on chain says how many decimals they use, so nothing can scale them. Their supply is shown as the raw integer the pallet stores and every scaled figure for them is null rather than a number — one of them holds 2.1 × 10²⁴ raw units, which at eighteen decimals would be 2.1 million tokens and at eight would be 21 thousand billion. Guessing eighteen because most ERC-20s use it would render perfectly and be wrong by up to ten orders of magnitude, so they are shown unscaled and left that way.',
        )
      : null,
    inventory.duplicateSymbols?.length
      ? el('p.note', {
          text: `${inventory.duplicateSymbols.join(', ')} each appear on more than one registered asset, and across the two pallets so does USDC. They are separate rows here and are never added together — every row on this page is keyed by its location, because a ticker is not an identifier on this chain.`,
        })
      : null,
    el(
      'div.tablewrap',
      null,
      el(
        'table.data',
        null,
        el(
          'thead',
          null,
          el(
            'tr',
            null,
            el('th', { text: 'Asset' }),
            el('th', { text: 'Name' }),
            el('th', { text: 'From' }),
            el('th.num', { text: 'Decimals' }),
            el('th.num', { text: 'Supply' }),
            el('th.num', { text: 'Holders' }),
            el('th', { text: 'Held by' }),
            el('th', { text: 'XCM location' }),
          ),
        ),
        body,
      ),
    ),
    el(
      'details.data-table',
      null,
      el('summary', { text: `The other ${inventory.counts.sibling} entries in the same registry — sibling parachain tokens, not bridged` }),
      el('p.note', {
        text:
          'These are `parents: 1` keys: a sibling parachain’s own token, registered on Asset Hub so it can be traded and transferred there. They came from inside Polkadot’s consensus system, so no bridge is involved and they are counted nowhere above. They are listed because the registry holds them and a page claiming to describe it should say what else is in it.',
      }),
      el(
        'div.tablewrap.scroll-y',
        null,
        el(
          'table.data',
          null,
          el(
            'thead',
            null,
            el(
              'tr',
              null,
              el('th', { text: 'Asset' }),
              el('th', { text: 'Name' }),
              el('th.num', { text: 'Para' }),
              el('th.num', { text: 'Decimals' }),
              el('th.num', { text: 'Supply' }),
              el('th.num', { text: 'Holders' }),
            ),
          ),
          siblings,
        ),
      ),
    ),
  )
}

/* ────────────────────────────────────────────────────────────── issued here, not bridged ── */

function issuedCard(inventory) {
  const body = el('tbody')
  for (const coin of inventory.localStables) {
    append(
      body,
      el(
        'tr',
        null,
        el('td.mono', { text: `${coin.symbol} · ${coin.assetId}` }),
        el('td', { text: coin.name ?? dash }),
        el('td', { text: coin.pallet }),
        el('td.num', { text: String(coin.decimals) }),
        el('td.num.mono', { text: amount(coin.supplyScaled), title: `${coin.supply} raw units` }),
        el('td.num', { text: formatCount(coin.accounts) }),
        el('td.mono', { text: shortAddr(coin.ownerAddress ?? coin.owner, 8, 6), title: coin.ownerAddress ?? coin.owner }),
      ),
    )
  }

  return el(
    'section.card',
    null,
    el(
      'header',
      null,
      el('h2', { text: 'Issued on Asset Hub, not bridged onto it' }),
      el('p.note', {
        text:
          'These two are in a separate block because their provenance is different in kind, not because they are a footnote — between them they are the largest stablecoin balance on the chain. They live in the `Assets` pallet under numeric ids, not in `ForeignAssets` under a location, and the `owner` and `issuer` fields are the issuers’ own accounts. There is no wrapper, no custodian and no bridge behind them, so they appear in no bar and no total above.',
      }),
    ),
    el(
      'div.tablewrap',
      null,
      el(
        'table.data',
        null,
        el(
          'thead',
          null,
          el(
            'tr',
            null,
            el('th', { text: 'Asset' }),
            el('th', { text: 'Name' }),
            el('th', { text: 'Pallet' }),
            el('th.num', { text: 'Decimals' }),
            el('th.num', { text: 'Supply' }),
            el('th.num', { text: 'Holders' }),
            el('th', { text: 'Owner' }),
          ),
        ),
        body,
      ),
    ),
    notice(
      'info',
      'Two USDCs exist on this chain and they are different assets',
      // The address is deliberately the SHORTENED form. A 42-character hex string is one
      // unbreakable word, and a notice is a plain paragraph with nowhere to wrap it — it
      // pushed the whole document 78px wider than a 390px viewport and gave every page a
      // horizontal scrollbar. The full key is on the row in the bridged table.
      'Circle’s is asset 1337 in the `Assets` pallet, above. Ethereum’s is the ERC-20 at 0xa0b869…06eb48, in `ForeignAssets` in the bridged table, with a supply three orders of magnitude smaller. Different ids, different backing, same three letters — and adding them together is a number that describes nothing.',
      'Tether’s is spelled `USDt`, with a lowercase t, because that is what the chain’s own metadata says. Ethereum’s bridged Tether is `USDT`. The spelling is the only thing distinguishing them in a symbol column, which is the argument for not having one.',
    ),
  )
}

/* ─────────────────────────────────────────────────────────────────────────────── the notes ── */

/**
 * Both operations return their own `notes` array, generated from the same payload the charts
 * are drawn from. They are rendered rather than paraphrased: a hand-written caveat drifts from
 * the data the first time the data changes and nothing says it has.
 */
function notesSection(inventory, holders, valued) {
  return el(
    'section.meta',
    null,
    el('h2', { text: 'Data notes' }),
    livenessNotes([valued.ok ? valued.data.meta?.liveness : null, inventory.meta?.liveness, holders.meta?.liveness].flat().filter(Boolean)),
    valued.ok ? el('h3', { text: 'The prices' }) : null,
    valued.ok ? wrapAnywhere(el('ul', null, ...(valued.data.notes ?? []).map((note) => el('li', { text: note })))) : null,
    el('h3', { text: 'The registry' }),
    wrapAnywhere(el('ul', null, ...(inventory.notes ?? []).map((note) => el('li', { text: note })))),
    el('h3', { text: 'The holder sweep' }),
    wrapAnywhere(el('ul', null, ...(holders.notes ?? []).map((note) => el('li', { text: note })))),
    el('p', {
      text: `The registry was read at Asset Hub block ${formatCount(inventory.chain.block)} and the holder sweep at block ${formatCount(holders.chain.block)}, runtime ${inventory.chain.specName} ${formatCount(inventory.chain.specVersion)}. Those are two reads a few blocks apart, so a transfer landing between them would show as a holding the inventory’s supply does not yet know about; each holding row carries its own block height for that reason.`,
    }),
    valued.ok
      ? el('p', {
          text: `The prices were read from Hydration at block ${formatCount(valued.data.hydrationChain.block)}, runtime ${valued.data.hydrationChain.specName} ${formatCount(valued.data.hydrationChain.specVersion)}, from the money-market oracle at ${valued.data.oracle.address} with a base currency unit of ${formatCount(valued.data.oracle.baseCurrencyUnit)}. Both the oracle address and the base unit are derived on every read rather than hardcoded, and the read is refused outright if the aDOT aToken, the pool and the addresses provider stop agreeing about each other.`,
        })
      : null,
    el('p', {
      text: `Every figure here is one reading of current state, fetched ${formatUtc(Date.parse(inventory.fetchedAt))}. Nothing on this page has a history behind it, so nothing on it can tell you whether a balance is usual — only what it is.`,
    }),
  )
}

/**
 * Three reads, and the third is allowed to fail on its own.
 *
 * Prices come from a different chain from everything else on this page, through a different
 * source module, and Hydration being unreachable must not take down a registry read that never
 * needed it (decision 0010 — unreachable is data). So the valuation is caught here and handed to
 * `render` as an outcome rather than thrown: the page then opens on a notice explaining what is
 * missing, and every block below it still draws.
 */
async function loadValuation() {
  try {
    return { ok: true, data: await read('prices', 'bridged') }
  } catch (error) {
    return {
      ok: false,
      kind: error?.kind ?? 'transport',
      message: error?.message ?? 'The pricing source could not be read.',
      advice: error?.advice ?? 'The valuation is unavailable on this read.',
    }
  }
}

renderPage({
  page: pageByKey('bridged'),
  intro:
    'Everything that enters Polkadot from another consensus system arrives through one registry on Asset Hub, and the storage key itself says where it came from. This is that registry read whole and, where a chain will price it, valued: what is bridged in and what it is worth, which parachain’s sovereign account is holding each asset now, and — because the holder map can be swept completely — whether the balances still add back up to the supply the pallet claims. Most of these assets have no on-chain price, so the dollar figure is a floor and the page names every asset it excludes.',
  load: () => Promise.all([read('asset-hub', 'bridged-inventory'), read('asset-hub', 'bridged-holders'), loadValuation()]),
  render,
  skeleton: ['stats', 'chart', 'chart'],
  loadingLabel: 'Reading Asset Hub’s ForeignAssets registry, sweeping every holder map, and pricing what Hydration can',
})
